services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - calligraphy-network
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8001

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - calligraphy-network
    env_file:
      - ./backend/.env
    environment:
      - HOST=0.0.0.0
      - PORT=8001

networks:
  calligraphy-network:
    driver: bridge